Implement a benchmark algorithm `Delaunay3D`
godotengine/godot-benchmarks pull request #39
Opened 2023-10-14 22:48 UTC by Chubercik

- Tried to implement 🟪**Algorithm**🟪 **_Delaunay3D_**: `Delaunay 1000 points in 3D` benchmark of the **Math** category proposed in #36.
- Turns out such a method is not exposed to the GDScript API.
- Updates will follow.

2023-10-14 23:21 UTC, Chubercik commented
If the [PR](https://github.com/godotengine/godot/pull/83353) mentioned above gets merged, completing this PR should be as easy as changing the insides of the `benchmark_delaunay3D()` function to:

```GDScript
Geometry3D.tetrahedralize_delaunay(scattered_points)
```

2023-10-22 22:32 UTC, Calinou requested changes
Same concerns as https://github.com/godotengine/godot-benchmarks/pull/38 apply to this PR, although this one isn't in a functional until 3D Delaunay triangulation is expsed to scripting.

2023-10-24 09:40 UTC, Chubercik commented
Committed an update that should be the final version. I haven't changed the number of points, because on my low-end laptop this benchmark takes `~4000ms` when running on a dev build of https://github.com/godotengine/godot/pull/83353/commits/bc78c832e98bb8e9b36a4d236d5ad9ce36de66c5.

2023-10-31 11:06 UTC, Geometror commented
@Chubercik Can you change this PR's status from draft to ready for review?

2023-10-31 11:11 UTC, Chubercik commented
The reason why I left it hanging as a draft is because until (probably) Godot 4.3 comes out, code from this PR won't be able to run - there is no such function as `Geometry3D.tetrahedralize_delaunay()` in `4.1`, upcoming `4.2` or even `master`, yet.

2023-11-06 18:39 UTC, Geometror commented
Oh sorry, I overlooked that. But I think it's fine either way. Could you add a `Depends on <link to PR>` to your PR description?

2023-11-06 22:40 UTC, Chubercik commented
Sure thing, the PR description has been updated.

2024-04-18 14:11 UTC, merged